# Generated by Django 4.2.2 on 2023-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_delete_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
