# Generated by Django 4.2.2 on 2023-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
