# Generated by Django 4.2.2 on 2023-06-15 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_alter_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='recipent',
            field=models.ManyToManyField(blank=True, null=True, related_name='reciedved_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
